### ISSUE TITLE
Is there a version that doesn't include vcpkg?

### ISSUE THREAD

**Issue by lokitkhemka** [yosh-matsuda/vscode-cpp-cuda-cmake-template#1]
I can never install vcpkg. It keeps failing and I cannot use this template because of that. I cannot even remove it, so that I can use it. I guess the entire CPP ecosystem is stupid and it's not your fault.

**Comment by lokitkhemka** [comment]
I managed to remove vcpkg. However, I cannot build the CUDA executable, I cannot find the `cuda_main` in the list of the build targets. Any help you can provide will be great?

**Comment by yosh-matsuda** [comment]
@lokitkhemka 

When CMake can find CUDA in the system, the projects in the `cuda` directory are available. You may see the message "No CUDA support" in the configure step of CMake (condition [here](https://github.com/yosh-matsuda/vscode-cpp-cuda-cmake-template/blob/805ae547ed85e19dad8f854ac2e1a35aff63ebab/cuda/CMakeLists.txt#L20)).

**Comment by lokitkhemka** [comment]
Hi,
I believe the issue was with cuda architecture specified in the cmake file(My GPU only supports upto 86, perhaps that's why). It works now.  Now, CMake is detecting CUDA fine and all the CUDA projects are showing up.

Thank you very much for your help.
